// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCas9qY1Y2b2FTrFptR0ZbXUTa-FBNCiJw',
    appId: '1:176858905485:web:32af78734e43cf1fb01bc4',
    messagingSenderId: '176858905485',
    projectId: 'its-school-d22f9',
    authDomain: 'its-school-d22f9.firebaseapp.com',
    storageBucket: 'its-school-d22f9.appspot.com',
    measurementId: 'G-43PBP8F0WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYXnRAWMUn2Cf_vDk8uYT5kilOx0Ze1zk',
    appId: '1:176858905485:android:a87a81859ad96ba7b01bc4',
    messagingSenderId: '176858905485',
    projectId: 'its-school-d22f9',
    storageBucket: 'its-school-d22f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI8Whaaz5RyN0G1LB2XtkWd-n0jzpTCp4',
    appId: '1:176858905485:ios:87d0f16a0a2d515eb01bc4',
    messagingSenderId: '176858905485',
    projectId: 'its-school-d22f9',
    storageBucket: 'its-school-d22f9.appspot.com',
    iosClientId: '176858905485-bfuj0luocnkesaarmmab7vnv519oht0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.teacherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI8Whaaz5RyN0G1LB2XtkWd-n0jzpTCp4',
    appId: '1:176858905485:ios:87d0f16a0a2d515eb01bc4',
    messagingSenderId: '176858905485',
    projectId: 'its-school-d22f9',
    storageBucket: 'its-school-d22f9.appspot.com',
    iosClientId: '176858905485-bfuj0luocnkesaarmmab7vnv519oht0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.teacherApp',
  );
}
